LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY MUXS IS
	PORT (
		S0 : IN STD_LOGIC;
		S1 : IN STD_LOGIC;
		S2 : IN STD_LOGIC;
		N : IN STD_LOGIC;
		Z : IN STD_LOGIC;
		V : IN STD_LOGIC;
		C : IN STD_LOGIC;
		output : OUT STD_LOGIC
	);
END MUXS;

ARCHITECTURE Behavioral OF MUXS IS
	SIGNAL ONE : STD_LOGIC := '1';
	SIGNAL ZERO : STD_LOGIC := '0';
BEGIN
	output <= ZERO AFTER 1 ns WHEN S0 = '0' AND S1 = '0' AND S2 = '0' ELSE
		ONE AFTER 1 ns WHEN S0 = '1' AND S1 = '0' AND S2 = '0' ELSE
		C AFTER 1 ns WHEN S0 = '0' AND S1 = '1' AND S2 = '0' ELSE
		V AFTER 1 ns WHEN S0 = '1' AND S1 = '1' AND S2 = '0' ELSE
		Z AFTER 1 ns WHEN S0 = '0' AND S1 = '0' AND S2 = '1' ELSE
		N AFTER 1 ns WHEN S0 = '1' AND S1 = '0' AND S2 = '1' ELSE
		(NOT C) AFTER 1 ns WHEN S0 = '0' AND S1 = '1' AND S2 = '1' ELSE
		(NOT Z) AFTER 1 ns WHEN S0 = '1' AND S1 = '1' AND S2 = '1' ELSE
		'0' AFTER 1 ns;
END Behavioral;