LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY MUXC IS
	PORT (
		S0 : IN STD_LOGIC;
        NA : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
        OPCODE : IN STD_LOGIC_VECTOR (7 DOWNTO 0);
        OUTPUT : OUT STD_LOGIC_VECTOR (7 DOWNTO 0)
	);
END MUXC;

ARCHITECTURE Behavioral OF MUXC IS
BEGIN
	OUTPUT <= OPCODE after 1 ns when S0 ='1' ELSE
	          NA  after 1 ns WHEN S0 ='0' ;
END Behavioral;